arifacts_root: artifacts

data_ingestion:
  root_dir: atifacts/data_ingestion
  source_URL: https://github.com/bharat856/Chicken-Fecal-Data/blob/main/Chicken-fecal-images.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion